version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.14.6
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - run:
          name: Run tests
          command: go test -v
      - run:
          name: Build binary
          command: go build -o server main.go
      - run:
          name: display binary
          command: ls -lrt
      - run:
          name: Run binary
          command: ./server