version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.14.6
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - run:
          name: Run tests
          command: go test -v
      - run:
          name: Build binary
          command: go build -o server main.go
      - run:
          name: display binary
          command: ls -lrt
      - run:
          name: Run binary
          command: ./server
deployment:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.14.6
    steps:
      - checkout
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run: go get -u github.com/stevenmatthewt/semantics
     release:
      branch: master
      commands:
      — go get github.com/mitchellh/gox
      — go get github.com/tcnksm/ghr
      — gox -ldflags "-X main.Version 'v1' -X main.BuildDate "210420220815” -output “server_{{.OS}}_{{.Arch}}"
      — ghr -t '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' -u 'amisha2515'-r 'test-golang' --replace `git describe --tags` 
workflows:
  version: 2.1
  build-deployment:
    jobs:
      - build
      - deployment:
          requires:
            - build